// Generated by CoffeeScript 1.9.0
(function() {
  var checkUpdate, responsesCount;

  responsesCount = null;

  checkUpdate = function() {
    return Tabletop.init({
      key: '1ZpK8G6wYlEEIOSVou_8rUInIDE7NgmIvOJ1XRfs6wuw',
      simpleSheet: true,
      callback: function(data, tabletop) {
        if (responsesCount == null) {
          responsesCount = data.length;
        }
        if (data.length > responsesCount) {
          $('audio').get(0).play();
          $('.go-go-lets-go').stop().slideDown().animate({
            opacity: 1.0
          }, 1000 * 5).slideUp();
        }
        return responsesCount = data.length;
      }
    });
  };

  $(function() {
    $('.go-go-lets-go').hide();
    return setInterval(function() {
      return checkUpdate();
    }, 1000 * 3);
  });

}).call(this);
