spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  security:
    user:
      name: tester
      password: password

jwt:
  secret: SECRET
