# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-cors'

gem 'puma'
gem 'rackup'

gem 'rerun'

gem 'ulid'

gem 'graphql'

gem 'faye-websocket'

group :development do
  gem 'rubocop', require: false
end
