# frozen_string_literal: true

guard :minitest do
  watch(/^test_(.*)\.rb$/) { '.' }
end

guard :rubocop do
  watch(/.+\.rb$/)
  watch(%r{(?:.+/)?\.rubocop(?:_todo)?\.yml$}) { |m| File.dirname(m[0]) }
end
