# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'rubocop'

gem 'activesupport'

gem 'puma'
gem 'rack-contrib'
gem 'rerun'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-cors'

gem 'graphql'
