spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true

jwt:
  secret: SECRET
