spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
  security:
    user:
      name: tester
      password: password

server:
  # port: 3000
  port: 8080
  servlet:
    encoding:
      force-response: true

jwt:
  secret: SECRET

cloudinary:
  url: ${CLOUDINARY_URL:cloudinary://key:secret@cloud}

redis:
  host: localhost
  port: 6379

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
